services:
  mikrotik-updater:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mikrotik-updater
    network_mode: host
    volumes:
      - ../data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/mikrotik.db
      - LOG_LEVEL=INFO
      - DEFAULT_USERNAME=admin
      - DEFAULT_PASSWORD=
    restart: unless-stopped
